# Generated by Django 3.2.3 on 2021-06-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0005_auto_20210530_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='books/%Y/%m/%d', verbose_name='Картинка')),
                ('name', models.CharField(max_length=40, verbose_name='Название книги')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('pages', models.IntegerField(verbose_name='Страниц')),
                ('binding', models.CharField(max_length=30, verbose_name='Переплет')),
                ('form', models.CharField(max_length=30, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('age', models.IntegerField(verbose_name='Возрастные ограничения')),
                ('quantity', models.IntegerField(verbose_name='Количество книг')),
                ('avtive', models.BooleanField(default=False, verbose_name='Активный')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Автор', to='directories.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Жанр', to='directories.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Издательство', to='directories.publisher')),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Серия', to='directories.series')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
