# Generated by Django 3.2.3 on 2021-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_auto_20210530_1945'),
        ('shop', '0002_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='Автор', to='directories.Author'),
        ),
    ]
