# Generated by Django 3.2.3 on 2021-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210617_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробнее об акции'),
        ),
    ]
