# Generated by Django 3.2.3 on 2021-05-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='number',
            field=models.IntegerField(verbose_name='Количество авторов'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.IntegerField(verbose_name='Серия книги'),
        ),
    ]
