# Generated by Django 3.2.3 on 2021-05-22 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_auto_20210523_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения в БД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
    ]
