# Generated by Django 3.2.3 on 2021-06-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='Номер мобильного телефона')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('address_1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес 1')),
                ('address_2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес 2')),
                ('info', models.CharField(blank=True, max_length=80, null=True, verbose_name='Дополнительная информация')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Логин', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
