# Generated by Django 3.2.3 on 2021-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Логин'),
        ),
    ]
