# Generated by Django 3.2.3 on 2021-06-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_userdetail_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'Подробности о пользователе', 'verbose_name_plural': 'Подробнее о пользователях'},
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
