# Generated by Django 3.2.3 on 2021-07-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdetail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер мобильного телефона'),
            preserve_default=False,
        ),
    ]
