# Generated by Django 3.2.3 on 2021-06-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(default=1, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
