# Generated by Django 3.2.3 on 2021-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210628_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='login',
            field=models.CharField(default=1, max_length=15, verbose_name='Login'),
            preserve_default=False,
        ),
    ]
